#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gTTS-token
Version  : 1.1.3
Release  : 9
URL      : https://files.pythonhosted.org/packages/e7/25/ca6e9cd3275bfc3097fe6b06cc31db6d3dfaf32e032e0f73fead9c9a03ce/gTTS-token-1.1.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/e7/25/ca6e9cd3275bfc3097fe6b06cc31db6d3dfaf32e032e0f73fead9c9a03ce/gTTS-token-1.1.3.tar.gz
Summary  : Calculates a token to run the Google Translate text to speech
Group    : Development/Tools
License  : MIT
Requires: gTTS-token-license = %{version}-%{release}
Requires: gTTS-token-python = %{version}-%{release}
Requires: gTTS-token-python3 = %{version}-%{release}
Requires: requests
BuildRequires : buildreq-distutils3
BuildRequires : requests

%description
gTTS-token
====

**gTTS-token** (Google Text to Speech token): A python implementation of the token validation of Google Translate

[![Build Status](https://travis-ci.org/Boudewijn26/gTTS-token.svg?branch=master)](https://travis-ci.org/Boudewijn26/gTTS-token)

Install
-------

    pip install gTTS-token

Description
-------

Google Translate requires a tk param when making a request to its translate API. This project provides an implementation for that algorithm in Python.

%package license
Summary: license components for the gTTS-token package.
Group: Default

%description license
license components for the gTTS-token package.


%package python
Summary: python components for the gTTS-token package.
Group: Default
Requires: gTTS-token-python3 = %{version}-%{release}
Provides: gtts-token-python

%description python
python components for the gTTS-token package.


%package python3
Summary: python3 components for the gTTS-token package.
Group: Default
Requires: python3-core
Provides: pypi(gTTS-token)

%description python3
python3 components for the gTTS-token package.


%prep
%setup -q -n gTTS-token-1.1.3
cd %{_builddir}/gTTS-token-1.1.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582933711
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gTTS-token
cp %{_builddir}/gTTS-token-1.1.3/LICENSE %{buildroot}/usr/share/package-licenses/gTTS-token/748ee85e743c7323d44803cdba103206fdb58874
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gTTS-token/748ee85e743c7323d44803cdba103206fdb58874

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
