#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gTTS-token
Version  : 1.1.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/4c/c8/dd58eba1464729095217d3acfc4f6581348c6f495ea3342ed7dbc9f9e133/gTTS-token-1.1.1.zip
Source0  : https://files.pythonhosted.org/packages/4c/c8/dd58eba1464729095217d3acfc4f6581348c6f495ea3342ed7dbc9f9e133/gTTS-token-1.1.1.zip
Summary  : Calculates a token to run the Google Translate text to speech
Group    : Development/Tools
License  : MIT
Requires: gTTS-token-python3
Requires: gTTS-token-python
Requires: requests
BuildRequires : buildreq-distutils3
BuildRequires : requests

%description
====

%package python
Summary: python components for the gTTS-token package.
Group: Default
Requires: gTTS-token-python3
Provides: gtts-token-python

%description python
python components for the gTTS-token package.


%package python3
Summary: python3 components for the gTTS-token package.
Group: Default
Requires: python3-core

%description python3
python3 components for the gTTS-token package.


%prep
%setup -q -n gTTS-token-1.1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534859825
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
